In [1]:
from sklearn import datasets

house_prices = datasets.load_boston()

print(house_prices.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [2]:
print(house_prices.target)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

Обработка данных перед построением моделей

In [1]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])



# Бинаризация
Эгот процесс применяется в тех случаях, когда мы хотим преобразовать
наши числовые значения в булевы. Воспользуемся встроенным методом для
бинаризации входных данных, установив значение 2.1 в качестве порогового.

In [2]:
data_bin = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\n binarezed data:\n", data_bin)


 binarezed data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


Как видите, все значения свыше 2 .1 принудительно устанавливаются равными 1. Остальные значения становятся равными О.

# Исключение среднего
Исключение среднего - методика предварительной обработки данных,
обычно используемая в машинном обучении. Как правило, из векторов признаков
(feature vectors) целесообразно исключать средние значения, чтобы
каждый признак (feature) центрировался на нуле. Эго делается с той целью,
чтобы исключить из рассмотрения смещение значений в векторах признаков.
Добавим следующие строки в тот же файл Python, который использовался
в предыдущем разделе.

In [6]:
print('\nBEFORE:')
print("mean=", input_data.mean(axis=0))
print('Std deviation=', input_data.std(axis=0))
# Исключение среднего
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:\n")
print("mean=", data_scaled.mean(axis=0))
print('Std deviation=', data_scaled.std(axis=0))


BEFORE:
mean= [ 3.775 -1.15  -1.3  ]
Std deviation= [3.12039661 6.36651396 4.0620192 ]

AFTER:

mean= [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation= [1. 1. 1.]


Нетрудно заметить, что среднее значение практически равно О, а стандартное
отклонение - 1.

# Масштабирование
В нашем векторе признаков каждое значение может меняться в некоторых
случайных пределах. Поэтому очень важно масштабировать признаки, чтобы
они представляли собой ровное игровое поле для тренировки алгоритма машинного
обучения. Мы не хотим, чтобы любой из признаков мог принимать
искусственно большое или малое значение лишь в силу природы измерений.

In [8]:
# Масштабирование MinMax
data_scaled_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
a = data_scaled_minmax.fit_transform(input_data)
print("\n Min max scaled data:\n", a)


 Min max scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


Каждая строка масштабирована так, чтобы максимальным значением было 1, а все остальные значения определялись относительно него

# Нормализация
Процесс нормализации заключается в изменении значений в векторе признаков
таким образом, чтобы для их измерения можно было использовать
одну общую шкалу. В машинном обучении используются различные формы
нормализации. В наиболее распространенных из них значения изменяются
так, чтобы их сумма была равна 1. Ll-нормализация, использующая метод
наименьших абсолютных отклонений (Least Absolute Deviations), обеспечивает
равенство 1 суммы абсолютных значений в каждом ряду. L2-норма11изация,
использующая метод наименьших квадратов, обеспечивает
равенство 1 суммы квадратов значений.
Вообще rоворя, техника Ll-нормализации считается более надежной по
сравнению с L2-нормализацией, поскольку она менее чувствительна к выбросам.
Очень часто данные содержат выбросы, и с этим ничеrо не поделаешь.
Мы хотим использовать безопасные методики, позволяющие игнорировать
выбросы в процессе вычислений. Если бы мы решали задачу, в которой выбросы
иrрают важную роль, то, вероятно, лучшим выбором была бы L2-нормализация.

In [9]:
# нормализация данных
data_norm1 = preprocessing.normalize(input_data, norm= 'l1')
data_norm2 = preprocessing.normalize(input_data, norm= 'l2')
print("\n normalized L1 data:\n", data_norm1 )
print("\n normalized L2 data:\n", data_norm2 )


 normalized L1 data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

 normalized L2 data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


# Кодирование меток
Как правило, в процессе классификации данных мы имеем дело со множесrвом
меток (labels). Ими моrут быть слова, числа или другие объекты.
Функции машинного обучения, входящие в библиотеку sklearn, ожидают,
что метки являются числами. Поэтому, если метки - это уже числа, мы можем
использовать их непосредсrвенно для того, чтобы начать тренировку.
Однако обычно это не так.
На практике метками служат слова, поскольку в таком виде они лучше
всего воспринимаются человеком. Мы помечаем тренировочные данные
словами, чтобы облегчить отслеживание соответсrвий. Для преобразования
слов в числа необходимо использовать кодирование. Под кодированием меток
(label encoding) подразумевается процесс преобразования словесных меток в
числовую форму. Благодаря этому алгоритмы моrут оперировать нашими
данными.

In [18]:
# Предоставление меток входных данных
labels = ['red', 'black', 'red', 'green', 'black', 'yellow',
'white']
# создание кодировщика и установление соотвествия
# между метками и числами 
encoder = preprocessing.LabelEncoder()
encoder.fit(labels)
#out 
print('\n Label mapping:\n')
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)


 Label mapping:

black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4


Преобразуем набор случайно упорядоченных меток, чтобы проверить работу кодировщика

In [19]:
test_labels = ['green', 'red', 'black']
encoder_val = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoder_val))



Labels = ['green', 'red', 'black']
Encoded values = [1, 2, 0]


Декодируем случайнный набор чисел

In [20]:
encoder_val1 = [3, 0, 4, 1]
decod_list = encoder.inverse_transform(encoder_val)
print("Encoded values =", encoder_val1)
print("\nDecode values =", list(decod_list))

Encoded values = [3, 0, 4, 1]

Decode values = ['green', 'red', 'black']


In [ ]:
#Логистический классификатор 53 страница 
# погуглить развернутую статистику (p, R, t-val) 
# как в Р языке но для питона!